### PR TITLE
Refactor Database and SQL files structure

### LINKED ISSUE #2: Refactor Database files structure
The files structure needs an update, I want to use a structure I already used in the [0 C.E. Database](https://github.com/0-C-E/Database) as a template.

Note: *Do not forget to update the Dockerfile*

### PR DESCRIPTION
**Pull request by Vianpyro**
Fixes #2

### CODE REVIEW

**Review by punith1213 — COMMENTED** [review]
USE smartcooking;
DELIMITER //

CREATE OR REPLACE PROCEDURE get_all_persons()
BEGIN
    SELECT person_id, name, email, registration_date, last_login, locale_id
    FROM person;
END //

CREATE OR REPLACE PROCEDURE get_person_by_id(IN p_person_id INT)
BEGIN
    SELECT person_id, name, email, registration_date, last_login, locale_id
    FROM person
    WHERE person_id = p_person_id;
END //

CREATE OR REPLACE PROCEDURE get_person_by_email(IN p_email VARCHAR(100))
BEGIN
    SELECT person_id, name, email, registration_date, last_login, locale_id
    FROM person
    WHERE email = p_email;
END //

CREATE OR REPLACE PROCEDURE get_recent_persons(IN p_start_date TIMESTAMP, IN p_end_date TIMESTAMP)
BEGIN
    SELECT person_id, name, email, registration_date
    FROM person
    WHERE registration_date BETWEEN p_start_date AND p_end_date;
END //

CREATE OR REPLACE PROCEDURE get_persons_by_locale(IN p_locale_id INT)
BEGIN
    SELECT person_id, name, email, registration_date
    FROM person
    WHERE locale_id = p_locale_id;
END //

CREATE OR REPLACE PROCEDURE get_person_recipe_engagement(IN p_person_id INT)
BEGIN
    SELECT re.recipe_id, re.engagement_type, re.engagement_date
    FROM recipe_engagement re
    WHERE re.person_id = p_person_id;
END //

DELIMITER ;


check this code

**Comment by Vianpyro** [comment]
Hi @punith1213,

Thank you so much for taking the time to review and suggest improvements to the stored procedures in my project. I truly appreciate the thought and effort you put into expanding the functionality, especially the additional fields and the new procedures.

While your suggestions are insightful and would undoubtedly enhance the flexibility of the database layer, I have concerns about privacy and data minimization. Specifically, I’ve intentionally avoided including fields like account creation date, last connection date, and locale to limit the exposure of potentially sensitive user information. This approach aligns with the principles I aim to follow in protecting user privacy within this project.

That being said, your ideas for additional procedures like filtering by locale and retrieving engagement data are fantastic and could be incredibly useful for future developments where privacy concerns are addressed differently. I’ve taken note of your contributions and may revisit them later if the project’s goals or requirements evolve in a way that aligns with your suggestions.

Thanks again for your input—it’s always great to have collaborators who bring fresh perspectives to the table!

Best regards,
@Vianpyro

**Comment by punith1213** [comment]
If you need any assistance, feel free to reach out to me.

**Comment by Vianpyro** [comment]
Thank you! Adding the email in the selected rows gave me the idea to add it masked!

**Comment by punith1213** [comment]
CREATE OR REPLACE PROCEDURE get_all_persons()
BEGIN
    SELECT 
        person_id,
        name,
        CONCAT(SUBSTRING(email, 1, 2), '***', SUBSTRING_INDEX(email, '@', -1)) AS masked_email,
        registration_date,
        last_login,
        locale_id
    FROM person;
END //

Explanation:
SUBSTRING(email, 1, 2): Extracts the first two characters of the email address.
'***': Adds asterisks as the mask.
SUBSTRING_INDEX(email, '@', -1): Extracts everything after the @ symbol (domain name).
CONCAT(...): Combines the masked part and the domain name to form the masked email.
Usage in Procedures:
You can apply this masking in your stored procedures where the email is selected.

**Pull request merged**
